export enum API_SYSTEMS {
    API_USERS_DASHBOAD_SERVICE = 'API_USERS_DASHBOAD_SERVICE',
}

export enum REPOSITORY_SYSTEMS {
    USERS_REPOSITORY = 'USERS_REPOSITORY',
}

export enum DASHBOARD_SYSTEMS {
    DASHBOARD_MODULE = 'DASHBOARD_MODULE',
}

export enum TRANSFORM_SYSTEMS {
    DASHBOARD_TRANSFORM = 'DASHBOARD_TRANSFORM',
}

export const INJECTION_SYSTEMS = {
    API: API_SYSTEMS,
    REPOSITORY: REPOSITORY_SYSTEMS,
    DASHBOARD: DASHBOARD_SYSTEMS,
    TRANSFORM: TRANSFORM_SYSTEMS,
};
